apiVersion: v2
name: tyk-oss
description: A Helm chart for Tyk Open Source gateway

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0
home: https://tyk.io/
sources:
  - https://github.com/TykTechnologies/tyk-charts/tree/main/tyk-oss
keywords:
  - api gateway
  - reverse proxy
  - api management
  - ingress
  - ingress controller
  - open source gateway
  - edge gateway
  - tyk
  - tyk gateway
  - tyk open source
dependencies:
  - name: tyk-gateway
    version: 1.0.0
    repository: file://../components/tyk-gateway
  - name: tyk-pump
    version: 1.0.0
    repository: file://../components/tyk-pump
    condition: global.components.pump
annotations:
  artifacthub.io/category: networking
  artifacthub.io/links: |
    - name: docs
      url: https://tyk.io/docs/
    - name: support
      url: https://community.tyk.io/
