apiVersion: v1
kind: Secret
metadata:
  name: secrets-tyk-single-dc
  namespace: {{ .Release.Namespace}}
  labels:
    app: secrets-tyk-single-dc
    release: {{ .Release.Name }}
type: Opaque
stringData:
  APISecret: "{{ .Values.global.secrets.APISecret}}"
