{{- if not .Values.global.secrets.useSecretName  -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-dev-portal.fullname" . }}
  labels:
    app: secrets-data-{{ include "tyk-dev-portal.fullname" . }}
    chart: {{ include "tyk-dev-portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  EnterprisePortalLicense: "{{ .Values.license }}"
  adminUserPassword: "{{ .Values.global.adminUser.password }}"
  EnterprisePortalStorageConnectionString: "{{ .Values.storage.database.connectionString }}"
  EnterprisePortalAwsAccessKeyId: "{{ .Values.storage.s3.awsAccessKeyid }}"
  EnterprisePortalAwsSecretAccessKey: "{{ .Values.storage.s3.awsSecretAccessKey }}"
{{- end }}
