{{- if or (not .Values.useSecretName) (not .Values.global.adminUser.useSecretName)  -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-dev-portal.fullname" . }}
  labels:
    app: secrets-data-{{ include "tyk-dev-portal.fullname" . }}
    chart: {{ include "tyk-dev-portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  {{- if not .Values.useSecretName }}
  DevPortalLicense: "{{ .Values.license }}"
  DevPortalDatabaseConnectionString: "{{ .Values.database.connectionString }}"
  DevPortalAwsAccessKeyId: "{{ .Values.storage.s3.awsAccessKeyid }}"
  DevPortalAwsSecretAccessKey: "{{ .Values.storage.s3.awsSecretAccessKey }}"
  {{- end }}
  {{- if not .Values.global.adminUser.useSecretName }}
  adminUserPassword: "{{ .Values.global.adminUser.password }}"
  {{- end }}
{{- end }}
