apiVersion: v1
kind: Service
metadata:
  name: dev-portal-svc-{{ include "tyk-dev-portal.fullname" . }}
  labels:
    app: dev-portal-svc-{{ include "tyk-dev-portal.fullname" . }}
    chart: {{ include "tyk-dev-portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
    name: {{ default "http" .Values.service.portName | quote }}
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "tyk-dev-portal.fullname" . }}
    release: {{ .Release.Name }}
{{- if eq .Values.service.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
