{{- if .Values.operatorSecret.enabled}}
apiVersion: v1
kind: Secret
metadata:
    name: tyk-operator-conf
type: Opaque
stringData:
    TYK_MODE: "ce"
    {{- if not .Values.global.secrets.useSecretName}}
    TYK_AUTH: "{{ .Values.global.secrets.APISecret}}"
    {{- end }}
    TYK_URL: "{{ include "tyk-oss.gwControlURL" . }}"
    TYK_ORG: "{{ .Values.operatorSecret.orgID}}"
{{- end }}
