apiVersion: apps/v1
kind: Deployment
metadata:
  name: pump-{{ include "tyk-pump.fullname" . }}
  labels:
    app: pump-{{ include "tyk-pump.fullname" . }}
    chart: {{ include "tyk-pump.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.pump.replicaCount }}
  selector:
    matchLabels:
      app: pump-{{ include "tyk-pump.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: pump-{{ include "tyk-pump.fullname" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.pump.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.pump.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.pump.tolerations }}
      tolerations:
{{ toYaml .Values.pump.tolerations | indent 8 }}
{{- end }}
{{- if .Values.pump.affinity }}
      affinity:
{{ toYaml .Values.pump.affinity | indent 8 }}
{{- end }}
      containers:
      - name: pump-{{ .Chart.Name }}
        image: "{{ .Values.pump.image.repository }}:{{ .Values.pump.image.tag }}"
        imagePullPolicy: {{ .Values.pump.image.pullPolicy }}
        workingDir: "/opt/tyk-pump"
        {{- if eq "prometheus" (include "tyk-pump.pumpType" .) }}
        ports:
          - name: prom-metrics
            containerPort: {{ .Values.pump.prometheusPump.port }}
        {{ end }}
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
        env:
          # Legacy support for Redis Cluster driver. Driver dropped in v3.0.0.
          - name: REDIGOCLUSTER_SHARDCOUNT
            value: "128"

         {{ if eq "prometheus" (include "tyk-pump.pumpType" .) }}
          # Configure Prometheus Pump for Tyk Pump
          - name: TYK_PMP_PUMPS_PROMETHEUS_TYPE
            value: prometheus
          - name: TYK_PMP_PUMPS_PROMETHEUS_META_ADDR
            value: "{{ .Values.pump.prometheusPump.host }}:{{ .Values.pump.prometheusPump.port }}"
          - name: TYK_PMP_PUMPS_PROMETHEUS_META_PATH
            value: "{{ .Values.pump.prometheusPump.path }}"
            {{ if .Values.pump.prometheusPump.customMetrics }}
          - name: TYK_PMP_PUMPS_PROMETHEUS_META_CUSTOMMETRICS
            value: "{{ .Values.pump.prometheusPump.customMetrics }}"
            {{ end }}
          {{ else if eq "postgres" (include "tyk-pump.pumpType" .) }}
          # SQL Pump
          - name: TYK_PMP_PUMPS_SQL_TYPE
            value: "sql"
          - name: TYK_PMP_PUMPS_SQL_META_TYPE
            value: "postgres"
          - name: TYK_PMP_PUMPS_SQL_META_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.global.secrets.useSecretName }} {{ .Values.global.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pump.fullname" . }} {{ end }}
                key: pgConnectionString
            
          # SQL Aggregate Pump
          - name: TYK_PMP_PUMPS_SQLAGGREGATE_TYPE
            value: "sql_aggregate"
          - name: TYK_PMP_PUMPS_SQLAGGREGATE_META_TYPE
            value: "postgres"
          - name: TYK_PMP_PUMPS_SQLAGGREGATE_META_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.global.secrets.useSecretName }} {{ .Values.global.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pump.fullname" . }} {{ end }}
                key: pgConnectionString
          {{ else if eq "mongo" (include "tyk-pump.pumpType" .) }}
          # Mongo Pump
          - name: TYK_PMP_PUMPS_MONGO_META_COLLECTIONNAME
            value: "tyk_analytics_pump"
          - name: TYK_PMP_PUMPS_MONGO_META_MONGOUSESSL
            value: "{{ default "false" .Values.global.mongo.useSSL }}"
          - name: TYK_PMP_PUMPS_MONGO_META_MONGOURL
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.global.secrets.useSecretName }} {{ .Values.global.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pump.fullname" . }} {{ end }}
                key: mongoURL
          
          # Mongo Aggregate Pump
          - name: TYK_PMP_PUMPS_MONGOAGGREGATE_TYPE
            value: "mongo-pump-aggregate"
          - name: TYK_PMP_PUMPS_MONGOAGGREGATE_META_MONGOUSESSL
            value:  "{{ default "false" .Values.global.mongo.useSSL }}"
          - name: TYK_PMP_PUMPS_MONGOAGGREGATE_META_MONGOURL
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.global.secrets.useSecretName }} {{ .Values.global.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pump.fullname" . }} {{ end }}
                key: mongoURL
          - name: TYK_PMP_PUMPS_MONGOAGGREGATE_META_COLLECTIONNAME
            value: "tyk_analytics_pump"
          - name: TYK_PMP_PUMPS_MONGOAGGREGATE_META_USEMIXEDCOLLECTION
            value: "true"
          {{ end }}
          {{ if eq "disabled" (include "tyk-pump.uptimePump" .) }}
          - name: TYK_PMP_DONTPURGEUPTIMEDATA
            value: "true"
          {{ else }}
          {{ if eq "postgres" (include "tyk-pump.uptimePump" .) }}
          # SQL Uptime Pump
          - name: TYK_PMP_UPTIMEPUMPCONFIG_UPTIMETYPE
            value: "sql"
          - name: TYK_PMP_UPTIMEPUMPCONFIG_TYPE
            value: "postgres"
          - name: TYK_PMP_UPTIMEPUMPCONFIG_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.global.secrets.useSecretName }} {{ .Values.global.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pump.fullname" . }} {{ end }}
                key: pgConnectionString
          {{ else if eq "mongo" (include "tyk-pump.uptimePump" .) }}
          # Mongo Uptime Pump
          - name: TYK_PMP_UPTIMEPUMPCONFIG_MONGOURL
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.global.secrets.useSecretName }} {{ .Values.global.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pump.fullname" . }} {{ end }}
                key: mongoURL
          {{ end }}
          {{ end }}

          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_ADDRS
            {{- if and .Values.global.redis.host .Values.global.redis.port }}
            value: "{{ .Values.global.redis.host }}:{{ .Values.global.redis.port }}"
            {{- else }}
            value: "{{ join "," .Values.global.redis.addrs }}"
            {{- end }}
          {{ if .Values.global.redis.enableSentinel }}
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_SENTINELPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.global.secrets.useSecretName }} {{ .Values.global.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pump.fullname" . }} {{ end }}
                key: redisSentinelPass
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_MASTERNAME
            value: "{{- .Values.global.redis.masterName -}}"
          {{ else if .Values.global.redis.enableCluster }}
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_ENABLECLUSTER
            value: "true"
          {{ else }}
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_MASTERNAME
            value: ""
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_ENABLECLUSTER
            value: "false"
          {{ end }}
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.global.secrets.useSecretName }} {{ .Values.global.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pump.fullname" . }} {{ end}}
                key: redisPass
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_REDISUSESSL
            value: "{{ default "false" .Values.global.redis.useSSL }}"

          - name: TYK_PMP_OMITCONFIGFILE
            value: "true"
          - name: TYK_PMP_ANALYTICSSTORAGETYPE
            value: "redis"
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_MAXIDLE
            value: "2000"
          - name: TYK_PMP_ANALYTICSSTORAGECONFIG_MAXACTIVE
            value: "4000"
          - name: TYK_PMP_PURGEDELAY
            value: "2"
          - name: TYK_PMP_UPTIMEPUMPCONFIG_COLLECTIONNAME
            value: "tyk_uptime_analytics"

            
        {{- if .Values.pump.extraEnvs }}
        {{- range $env := .Values.pump.extraEnvs }}
          - name: {{ $env.name }}
            value: {{ $env.value | quote }}
        {{- end }}
        {{- end }}

        command: ["/opt/tyk-pump/tyk-pump"]
        volumeMounts:
          {{- if .Values.pump.mounts }}
          {{- range $secret := .Values.pump.mounts }}
          - name: {{ $.Release.Name }}-pump-secret-{{ $secret.name }}
            mountPath: {{ $secret.mountPath }}
          {{- end }}
          {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if .Values.pump.securityContext }}
      securityContext:
      {{- toYaml .Values.pump.securityContext | nindent 10 }}
      {{- end }}
      volumes:
        {{- if .Values.pump.mounts }}
        {{- range $secret := .Values.pump.mounts }}
        - name: {{ $.Release.Name }}-pump-secret-{{ $secret.name }}
          secret:
            secretName: {{ $.Release.Name }}-pump-secret-{{ $secret.name }}
        {{- end }}
        {{- end }}
