{{- if not .Values.secrets.useSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-pump.fullname" . }}
  labels:
    app: secrets-data-{{ include "tyk-pump.fullname" . }}
    chart: {{ include "tyk-pump.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  redisPass: "{{ .Values.redis.pass }}"
  redisSentinelPass: "{{ .Values.redis.sentinelPass }}"
  mongoURL: {{ include "tyk-pump.mongo_url" . | quote }}
  pgConnectionString: {{ include "tyk-pump.pg_connection_string" . }}
{{- end }}
