apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ include "tyk-stack.fullname" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    app: secret-{{ include "tyk-stack.fullname" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  APISecret: "{{ .Values.global.secrets.APISecret}}"
