apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-stack.fullname" }}
  namespace: {{ .Release.Namespace}}
  labels:
    app: secrets-{{ include "tyk-stack.fullname" }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  APISecret: "{{ .Values.global.secrets.APISecret}}"
