{{ if and .Values.gateway.tls.useDefaultTykCertificate .Values.gateway.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gateway.tls.secretName }}
type: Opaque
data:
  cert.pem: |-
    {{ .Files.Get "certs/cert.pem" | b64enc }}
{{ end }}