{{- if not .Values.secrets.useSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-gateway.fullname" . }}
  labels:
    app: secrets-data-{{ include "tyk-gateway.fullname" . }}
    chart: {{ include "tyk-gateway.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  redisPass: "{{ .Values.redis.pass }}"
  redisSentinelPass: "{{ .Values.redis.sentinelPass }}"
  APISecret: "{{ .Values.secrets.APISecret }}"
{{- end }}
