apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tyk-enterprise-portal.fullname" . }}
  labels:
    app: {{ include "tyk-enterprise-portal.fullname" . }}
    chart: {{ include "tyk-enterprise-portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: enterprise-portal-svc-{{ include "tyk-enterprise-portal.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ include "tyk-enterprise-portal.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "tyk-enterprise-portal.fullname" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: enterprise-portal-{{ .Chart.Name }}
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
        env:
          - name: PORTAL_LICENSEKEY
            valueFrom:
              secretKeyRef:
                {{ if .Values.global.secrets.useSecretName }}
                name: {{ .Values.global.secrets.useSecretName }}
                {{ else }}
                name: secrets-{{ include "tyk-enterprise-portal.fullname" . }}
                {{ end }}
                key: EnterprisePortalLicense
          - name: PORTAL_HOST_PORT
            value: "{{ .Values.containerPort }}"
          - name: ADMIN_EMAIL
            value: "{{ .Values.global.adminUser.email }}"
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                {{ if .Values.global.secrets.useSecretName }}
                name: {{ .Values.global.secrets.useSecretName }}
                {{ else }}
                name: secrets-{{ include "tyk-enterprise-portal.fullname" . }}
                {{ end }}
                key: EnterprisePortalAdminPassword
          - name: PORTAL_DATABASE_DIALECT
            value: "{{ .Values.storage.database.type }}"
          - name: PORTAL_DATABASE_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                {{ if .Values.global.secrets.useSecretName }}
                name: {{ .Values.global.secrets.useSecretName }}
                {{ else }}
                name: secrets-{{ include "tyk-enterprise-portal.fullname" . }}
                {{ end }}
                key: EnterprisePortalStorgeConnectionString
          - name: PORTAL_THEMING_THEME
            value: "default"
          - name: PORTAL_THEMING_PATH
            value: "./themes"
          - name: PROVIDER_NAME
            value: "tyk"
          - name: TYK_URL
          {{ if ne .Values.overrideTykDashUrl ""}}
            value: {{ .Values.overrideTykDashUrl}}
          {{ else}}
            value: "http{{ if .Values.global.tls.dashboard }}s{{ end }}://dashboard-svc-{{ .Release.Name }}-tyk-dashboard.{{ .Release.Namespace }}.svc:{{ .Values.global.servicePorts.dashboard }}"
          {{- end }}
          - name: TYK_AUTH
            valueFrom:
              secretKeyRef:
                {{ if .Values.global.secrets.useSecretName }}
                name: {{ .Values.global.secrets.useSecretName }}
                {{ else }}
                name: {{ .Values.global.secrets.enterprisePortal}}
                {{ end }}
                key: TYK_AUTH
          - name: TYK_ORG
            valueFrom:
              secretKeyRef:
                {{ if .Values.global.secrets.useSecretName }}
                name: {{ .Values.global.secrets.useSecretName }}
                {{ else }}
                name: {{ .Values.global.secrets.enterprisePortal}}
                {{ end }}
                key: TYK_ORG
        {{- if .Values.extraEnvs }}
        {{- range $env := .Values.extraEnvs }}
          - name: {{ $env.name }}
            value: {{ $env.value | quote }}
        {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        command: ["/opt/portal/dev-portal"]
        {{- if .Values.global.bootstrap.enterprisePortal }}
        args: ["--bootstrap", "--provider-data={\"URL\":\"$(TYK_URL)\",\"Secret\":\"$(TYK_AUTH)\",\"OrgID\":\"$(TYK_ORG)\"}", "-user=$(ADMIN_EMAIL)", "-pass=$(ADMIN_PASSWORD)"]
        {{- end }}
        workingDir: /opt/portal
        ports:
        - containerPort: {{ .Values.containerPort }}
        volumeMounts:
          - name: enterprise-portal-pvc-{{ include "tyk-enterprise-portal.fullname" . }}
            mountPath: /opt/portal/public/system/api_details
            subPath: api_details
          - name: enterprise-portal-pvc-{{ include "tyk-enterprise-portal.fullname" . }}
            mountPath: /opt/portal/public/system/versions
            subPath: versions
          - name: enterprise-portal-pvc-{{ include "tyk-enterprise-portal.fullname" . }}
            mountPath: /opt/portal/public/system/products
            subPath: products
          - name: enterprise-portal-pvc-{{ include "tyk-enterprise-portal.fullname" . }}
            mountPath: /opt/portal/public/system/posts
            subPath: posts
          - name: enterprise-portal-pvc-{{ include "tyk-enterprise-portal.fullname" . }}
            mountPath: /opt/portal/public/system/media_libraries
            subPath: media_libraries
          - name: enterprise-portal-pvc-{{ include "tyk-enterprise-portal.fullname" . }}
            mountPath: /opt/portal/public/system/image_blocks
            subPath: image_blocks
          - name: enterprise-portal-pvc-{{ include "tyk-enterprise-portal.fullname" . }}
            mountPath: /opt/portal/public/system/assets
            subPath: assets
          - name: enterprise-portal-pvc-{{ include "tyk-enterprise-portal.fullname" . }}
            mountPath: /tmp/tyk-portal
            subPath: tyk-portal
          - name: enterprise-portal-pvc-{{ include "tyk-enterprise-portal.fullname" . }}
            mountPath: /opt/portal/themes
            subPath: themes
          {{- if eq .Values.storage.database.type "sqlite3" }}
          - name: enterprise-portal-pvc-{{ include "tyk-enterprise-portal.fullname" . }}
            mountPath: /opt/portal/db
            subPath: db
          {{- end }}
        livenessProbe:
          httpGet:
            scheme: "HTTP{{ if .Values.global.tls.enterprisePortal }}S{{ end }}"
            path: /
            port: {{ .Values.containerPort }}
          initialDelaySeconds: {{ default 60 .Values.livenessProbe.initialDelaySeconds}}
          periodSeconds: 2
          timeoutSeconds: 3
          failureThreshold: 2
        readinessProbe:
          httpGet:
            scheme: "HTTP{{ if .Values.global.tls.enterprisePortal }}S{{ end }}"
            path: /
            port: {{ .Values.containerPort }}
          initialDelaySeconds: {{ default 60 .Values.readinessProbe.initialDelaySeconds}}
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      {{- if .Values.securityContext }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end}}
  volumeClaimTemplates:
  - metadata:
      name: enterprise-portal-pvc-{{ include "tyk-enterprise-portal.fullname" . }}
      {{- if .Values.storage.persistence.annotations }}
      annotations:
      {{- range $key, $value := .Values.storage.persistence.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      {{- if .Values.storage.persistence.labels }}
      labels:
      {{- range $key, $value := .Values.storage.persistence.labels }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    spec:
      accessModes:
      {{- range .Values.storage.persistence.accessModes }}
        - {{ . | quote }}
      {{- end }}
      storageClassName: {{ .Values.storage.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.storage.persistence.size | quote }}
      {{- if .Values.storage.persistence.selector }}
      selector:
      {{- range $key, $value := .Values.storage.persistence.selector }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
