apiVersion: v2
name: tyk-gateway
version: 2.2.0
description: A Helm chart for deploying the open source Tyk Gateway.
  Tyk Gateway is a fully open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols.
  Tyk Gateway is provided ‘Batteries-included’, with no feature lockout. It enables organisations and businesses around
  the world to protect, secure, and process APIs and well as review and audit the consumed apis.
icon: https://tyk.io/wp-content/uploads/2023/11/Tyk-helm-icon-02.png
home: https://tyk.io/
sources:
  - https://github.com/TykTechnologies/tyk-charts/tree/main/components/tyk-gateway
keywords:
  - api gateway
  - reverse proxy
  - api management
  - ingress
  - ingress controller
  - open source gateway
  - edge gateway
  - api microgateway
  - tyk
  - tyk gateway
  - apis
annotations:
  artifacthub.io/category: networking
  artifacthub.io/links: |
    - name: docs
      url: https://tyk.io/docs/
    - name: support
      url: https://community.tyk.io/
