apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tyk-data-plane
  namespace: {{ .Release.Namespace}}
  labels:
    app: secrets-tyk-data-plane
    release: {{ .Release.Name }}
data:
  rpcConnString: "{{ .Values.global.rpc.connectionString }}"
  rpcUseSSL: "{{ .Values.global.rpc.useSSL}}"
  rpcSslInsecureSkipVerify: "{{ .Values.global.rpc.sslInsecureSkipVerify}}"
