apiVersion: v1
kind: Secret
metadata:
  name: secrets-tyk-data-plane
  namespace: {{ .Release.Namespace}}
  labels:
    app: secrets-tyk-data-plane
    release: {{ .Release.Name }}
type: Opaque
stringData:
  rpcKey: "{{ .Values.global.remoteControlPlane.orgId }}"
  apiKey: "{{  .Values.global.remoteControlPlane.userApiKey }}"
  APISecret: "{{ .Values.global.secrets.APISecret}}"
  groupID: "{{ .Values.global.remoteControlPlane.groupID}}"
