apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-data-plane.fullname" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    app: secrets-tyk-data-plane
    release: {{ .Release.Name }}
type: Opaque
stringData:
  APISecret: "{{ .Values.global.secrets.APISecret}}"
