{{- if not .Values.global.secrets.useSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: hybrid-pump-secrets-{{ include "tyk-pump.fullname" . }}
  labels:
    app: hybrid-pump-secrets-data-{{ include "tyk-pump.fullname" . }}
    chart: {{ include "tyk-pump.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  connectionString: "{{ .Values.pump.hybridPump.connectionString }}"
  userApiKey: "{{ .Values.pump.hybridPump.userApiKey }}"
  groupID: "{{ .Values.pump.hybridPump.groupID}}"
  orgID: "{{ .Values.pump.hybridPump.orgId }}"
{{- end }}
