{{- if not ( and ((.Values.global.redis.passSecret).name) ((.Values.global.mongo.connectionURLSecret).name) ((.Values.global.postgres.connectionStringSecret).name)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-pump.fullname" . }}
  labels:
    app: secrets-data-{{ include "tyk-pump.fullname" . }}
    chart: {{ include "tyk-pump.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
{{- if not ((.Values.global.redis.passSecret).name) }}
  redisPass: "{{ .Values.global.redis.pass }}"
{{- end }}

{{- if not ((.Values.global.mongo.connectionURLSecret).name) }}
  mongoURL: {{ include "tyk-pump.mongo_url" . | quote }}
{{- end }}

{{- if not ((.Values.global.postgres.connectionStringSecret).name) }}
  pgConnectionString: {{ include "tyk-pump.pg_connection_string" . }}
{{- end }}
{{- end }}
