{{- range $secret := $.Values.pump.mounts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-pump-secret-{{ $secret.name }}
  labels:
    app: pump-secret-{{ $secret.name }}-{{ include "tyk-pump.fullname" $ }}
    chart: {{ include "tyk-pump.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
type: Opaque
data:
  {{ $secret.filename }}: |-
{{ $.Files.Get (printf "mounts/%s" $secret.filename) | b64enc | indent 4 }}
---
{{- end }}