
apiVersion: v1
{{ with  .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{ end }}
kind: ServiceAccount
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidefinitions
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidescriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidescriptions/finalizers
  verbs:
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidescriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - operatorcontexts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - operatorcontexts/finalizers
  verbs:
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - operatorcontexts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalapicatalogues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalapicatalogues/finalizers
  verbs:
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalapicatalogues/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - securitypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - securitypolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - subgraphs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - subgraphs/finalizers
  verbs:
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - subgraphs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - supergraphs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - supergraphs/finalizers
  verbs:
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - supergraphs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - tykoasapidefinitions
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - tykoasapidefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - tykoasapidefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - tykstreamsapidefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - tykstreamsapidefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - tykstreamsapidefinitions/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tyk-operator
  name: {{ include "tyk-operator-helm.fullname" . }}-tykstreamsapidefinition-editor-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - tykstreamsapidefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - tykstreamsapidefinitions/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tyk-operator
  name: {{ include "tyk-operator-helm.fullname" . }}-tykstreamsapidefinition-viewer-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - tykstreamsapidefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - tykstreamsapidefinitions/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tyk-operator-helm.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "tyk-operator-helm.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tyk-operator-helm.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "tyk-operator-helm.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tyk-operator-helm.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "tyk-operator-helm.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: tyk-operator-controller-manager
  name: {{ include "tyk-operator-helm.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.metricsPort }}
    targetPort: {{ .Values.metricsPort }}
  selector:
    control-plane: tyk-operator-controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: {{ .Values.webhooks.port | default .Values.webhookPort }}
  selector:
    control-plane: tyk-operator-controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
{{- with .Values.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    control-plane: tyk-operator-controller-manager
  name: {{ include "tyk-operator-helm.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: tyk-operator-controller-manager
  template:
    metadata:
{{- with .Values.podAnnotations }}
      annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
      labels:
        control-plane: tyk-operator-controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        - --health-probe-bind-address=:{{ .Values.healthProbePort }}
        - --metrics-bind-address=:{{ .Values.metricsPort }}
        - --webhook-port={{ .Values.webhooks.port | default .Values.webhookPort }}
        - --metrics-secure={{ .Values.secureMetrics }}
        command:
        - /manager
{{- with .Values.envVars }}
        env:
{{- toYaml . | nindent 10 }}
{{- end }}
{{- with .Values.envFrom }}
        envFrom:
{{- toYaml . | nindent 10 }}
{{- end }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.healthProbePort }}
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: {{ .Values.webhooks.port | default .Values.webhookPort }}
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.healthProbePort }}
          initialDelaySeconds: 5
          periodSeconds: 10
{{- with .Values.resources }}
        resources:
{{- toYaml . | nindent 10 }}
{{- end }}
{{- with .Values.securityContext }}
        securityContext:
{{- toYaml . | nindent 10 }}
{{- end }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        {{ if .Values.extraVolumeMounts }}
            {{ toYaml .Values.extraVolumeMounts | nindent 8}}
          {{ end }}
      hostNetwork: {{ .Values.hostNetwork | default false }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "tyk-operator-helm.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
      {{ if .Values.extraVolumes }}
       {{ toYaml .Values.extraVolumes | nindent 6 }}
        {{ end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ include "tyk-operator-helm.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ include "tyk-operator-helm.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "tyk-operator-helm.fullname" . }}-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
{{ if .Values.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: tyk-operator-controller-manager
  name: {{ include "tyk-operator-helm.fullname" . }}-controller-manager-metrics-monitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: tyk-operator-controller-manager
{{ end }} 
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "tyk-operator-helm.fullname" . }}-serving-cert
  name: {{ include "tyk-operator-helm.fullname" . }}-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "tyk-operator-helm.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-tyk-tyk-io-v1alpha1-apidefinition
  failurePolicy: Fail
  name: mapidefinition.kb.io
  rules:
  - apiGroups:
    - tyk.tyk.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apidefinitions
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "tyk-operator-helm.fullname" . }}-serving-cert
  name: {{ include "tyk-operator-helm.fullname" . }}-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "tyk-operator-helm.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-tyk-tyk-io-v1alpha1-apidefinition
  failurePolicy: Fail
  name: vapidefinition.kb.io
  rules:
  - apiGroups:
    - tyk.tyk.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apidefinitions
  sideEffects: None
