apiVersion: apps/v1
kind: {{ .Values.gateway.kind }}
metadata:
  name: gateway-{{ include "tyk-gateway.fullname" . }}
  labels:
    app: gateway-{{ include "tyk-gateway.fullname" . }}
    chart: {{ include "tyk-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if eq .Values.gateway.kind "Deployment" }}
  replicas: {{ .Values.gateway.replicaCount }}
{{- end }}
  minReadySeconds: 5
{{- if eq .Values.gateway.kind "Deployment" }}
  strategy:
{{- else }}
  updateStrategy:
{{- end }}
{{- if ((.Values.gateway.strategy).type) }}
    type: {{ .Values.gateway.strategy.type }}
{{- else }}
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
{{- if eq .Values.gateway.kind "Deployment" }}
      maxSurge: 2
{{- end }}
      maxUnavailable: 1
{{- end }}
  selector:
    matchLabels:
      app: gateway-{{ include "tyk-gateway.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.gateway.podAnnotations }}
      annotations: {{ toYaml .Values.gateway.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        app: gateway-{{ include "tyk-gateway.fullname" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.gateway.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.gateway.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.gateway.tolerations }}
      tolerations:
{{ toYaml .Values.gateway.tolerations | indent 8 }}
{{- end }}
{{- if .Values.gateway.affinity }}
      affinity:
{{ toYaml .Values.gateway.affinity | indent 8 }}
{{- end }}
      {{- with .Values.gateway.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: "setup-directories"
        image: busybox:1.32
        command: ['sh','-c','mkdir -p apps middleware policies && touch policies/policies.json']
        workingDir: /mnt/tyk-gateway
        volumeMounts:
          - name: tyk-scratch
            mountPath: /mnt/tyk-gateway
      containers:
      - name: gateway-{{ .Chart.Name }}
        image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
        imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
        env:
          - name: TYK_GW_LISTENPORT
            value: "{{ .Values.global.servicePorts.gateway }}"
          {{ if .Values.global.components.dashboard}}
          - name: TYK_GW_USEDBAPPCONFIGS
            value: "true"
           {{- end }}
          {{- if .Values.gateway.control.enabled }}
          - name: TYK_GW_CONTROLAPIPORT
            value: "{{ .Values.gateway.control.containerPort }}"
          {{- end }}

          # Legacy support for Redis Cluster driver. Driver dropped in v3.0.0.
          - name: REDIGOCLUSTER_SHARDCOUNT
            value: "128"
          - name: TYK_GW_STORAGE_TYPE
            value: "redis"
          - name: TYK_GW_STORAGE_ADDRS
            value: {{ include "tyk-gateway.redis_url" . | quote }}
          {{ if .Values.global.redis.enableSentinel }}
          - name: TYK_GW_STORAGE_SENTINELPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "tyk-gateway.redis_secret_name" . }}
                key: {{ include "tyk-gateway.redis_secret_key" . }}
          - name: TYK_GW_STORAGE_MASTERNAME
            value: "{{- .Values.global.redis.masterName -}}"
         {{ else if .Values.global.redis.enableCluster }}
          - name: TYK_GW_STORAGE_ENABLECLUSTER
            value: "true"
         {{ else }}
          - name: TYK_GW_STORAGE_ENABLECLUSTER
            value: "false"
         {{ end }}

          - name: TYK_GW_STORAGE_DATABASE
            value: "{{ default "0" .Values.global.redis.storage.database }}"
          - name: TYK_GW_STORAGE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "tyk-gateway.redis_secret_name" . }}
                key: {{ include "tyk-gateway.redis_secret_key" . }}
          - name: TYK_GW_STORAGE_USESSL
            value: "{{ default "false" .Values.global.redis.useSSL }}"
          - name: TYK_GW_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.global.secrets.useSecretName }} {{ .Values.global.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-gateway.fullname" . }} {{ end}}
                key: APISecret
          - name: TYK_GW_NODESECRET
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.global.secrets.useSecretName }} {{ .Values.global.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-gateway.fullname" . }} {{ end}}
                key: APISecret

          - name: TYK_GW_POLICIES_ALLOWEXPLICITPOLICYID
            value: "true"
          - name: TYK_GW_HTTPSERVEROPTIONS_USESSL
            value: "{{ .Values.global.tls.gateway }}"
          - name: TYK_GW_TEMPLATEPATH
            value: "/opt/tyk-gateway/templates"
          - name: TYK_GW_TYKJSPATH
            value: "/opt/tyk-gateway/js/tyk.js"
          - name: TYK_GW_MIDDLEWAREPATH
            value: "/mnt/tyk-gateway/middleware"
          - name: TYK_GW_APPPATH
            value: "/mnt/tyk-gateway/apps"
          - name: TYK_GW_POLICIES_POLICYPATH
            value: "/mnt/tyk-gateway/policies"
          - name: TYK_GW_STORAGE_MAXIDLE
            value: "1000"
          - name: TYK_GW_OPTIMISATIONSUSEASYNCSESSIONWRITE
            value: "true"
          - name: TYK_GW_ENABLENONTRANSACTIONALRATELIMITER
            value: "true"
          - name: TYK_GW_POLICIES_POLICYSOURCE
        {{- if .Values.global.remoteControlPlane.enabled }}
            value: "rpc"
        {{- else}}
            value: "file"
        {{- end}}
        {{- if .Values.global.remoteControlPlane.enabled }}
          - name: TYK_GW_ANALYTICSCONFIG_TYPE
            value: "{{.Values.gateway.analyticsConfigType}}"
          - name: TYK_GW_SLAVEOPTIONS_USERPC
            value: "true"
          - name: TYK_GW_AUTHOVERRIDE_FORCEAUTHPROVIDER
            value: "true"
          - name: TYK_GW_AUTHOVERRIDE_AUTHPROVIDER_STORAGEENGINE
            value: "rpc"
          - name: TYK_GW_SLAVEOPTIONS_RPCKEY
            value: "{{ .Values.global.remoteControlPlane.orgId }}"
          - name: TYK_GW_SLAVEOPTIONS_APIKEY
            value: "{{  .Values.global.remoteControlPlane.userApiKey }}"
          - name: TYK_GW_SLAVEOPTIONS_GROUPID
            value: "{{ .Values.global.remoteControlPlane.groupID}}"
          - name: TYK_GW_SLAVEOPTIONS_CONNECTIONSTRING
            value: "{{ .Values.global.remoteControlPlane.connectionString }}"
          - name: TYK_GW_SLAVEOPTIONS_USESSL
            value: "{{ .Values.global.remoteControlPlane.useSSL}}"
          - name: TYK_GW_SLAVEOPTIONS_SSLINSECURESKIPVERIFY
            value: "{{ .Values.global.remoteControlPlane.sslInsecureSkipVerify}}"
        {{- end}}
          - name: TYK_GW_POLICIES_POLICYRECORDNAME
        {{- if .Values.global.remoteControlPlane.enabled }}
            value: "tyk_policies"
        {{- else}}
            value: "/mnt/tyk-gateway/policies/policies.json"
        {{- end}}
          - name: TYK_GW_HASHKEYS
            value: "true"
          - name: TYK_GW_HASHKEYFUNCTION
            value: "murmur128"
          - name: TYK_GW_HTTPSERVEROPTIONS_ENABLEWEBSOCKETS
            value: "true"
          - name: TYK_GW_HTTPSERVEROPTIONS_MINVERSION
            value: "771"
          - name: TYK_GW_HTTPSERVEROPTIONS_CERTIFICATES
            value: '[{"domain_name": "*", "cert_file": "/etc/certs/tls.crt", "key_file": "/etc/certs/tls.key"}]'
          - name: TYK_GW_ALLOWINSECURECONFIGS
            value: "true"
          - name: TYK_GW_COPROCESSOPTIONS_ENABLECOPROCESS
            value: "true"
          - name: TYK_GW_GLOBALSESSIONLIFETIME
            value: "100"
          - name: TYK_GW_MAXIDLECONNSPERHOST
            value: "500"
          - name: TYK_GW_ENABLECUSTOMDOMAINS
            value: "true"
          - name: TYK_GW_PIDFILELOCATION
            value: "/mnt/tyk-gateway/tyk.pid"

          - name: TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING
            value: "{{ include "tyk-gateway.dash_proto" . }}://dashboard-svc-{{ .Release.Name }}-tyk-dashboard.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.servicePorts.dashboard}}"
          - name: TYK_GW_POLICIES_POLICYCONNECTIONSTRING
            value: "{{ include "tyk-gateway.dash_proto" . }}://dashboard-svc-{{ .Release.Name }}tyk-dashboard.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.servicePorts.dashboard }}"

        {{- if .Values.global.components }}
        {{- if .Values.global.components.pump }}
          - name: TYK_GW_ENABLEANALYTICS
            value: "true"
        {{- end }}
        {{- end }}

        {{- if .Values.gateway.sharding.enabled }}
          - name: TYK_GW_DBAPPCONFOPTIONS_NODEISSEGMENTED
            value: "{{ .Values.gateway.sharding.enabled }}"
          - name: TYK_GW_DBAPPCONFOPTIONS_TAGS
            value: "{{ .Values.gateway.sharding.tags }}"
        {{- else }}
          - name: TYK_GW_DBAPPCONFOPTIONS_NODEISSEGMENTED
            value: "false"
        {{- end }}

        {{- if .Values.gateway.extraEnvs }}
        {{- include "tyk-gateway.tplvalues.render" ( dict "value" .Values.gateway.extraEnvs "context" $ ) | nindent 10 }}
        {{- end }}
        command: ["/opt/tyk-gateway/tyk"]
        workingDir: /opt/tyk-gateway
        ports:
        - containerPort: {{ .Values.global.servicePorts.gateway }}
        {{- if .Values.gateway.control.enabled }}
        - containerPort: {{ .Values.gateway.control.containerPort }}
        {{- end }}
        resources:
{{ toYaml .Values.gateway.resources | indent 12 }}
        volumeMounts:
          {{ if .Values.global.tls.gateway }}
          - name: {{ .Values.gateway.tls.secretName }}
            mountPath: /etc/certs
          {{ end }}
          - name: tyk-scratch
            mountPath: /mnt/tyk-gateway
          {{- if .Values.gateway.extraVolumeMounts }}
          {{- include "tyk-gateway.tplvalues.render" (dict "value" .Values.gateway.extraVolumeMounts "context" $) | nindent 10 }}
          {{- end }}
        livenessProbe:
          httpGet:
            scheme: "HTTP{{ if .Values.global.tls.gateway }}S{{ end }}"
            path: /hello
            {{- if and .Values.gateway.control.enabled (or (semverCompare ">= 3.2.0" (include "tyk-gateway.gateway-version" . )) (semverCompare ">=3.0.4 < 3.1.0" (include "tyk-gateway.gateway-version" .))) }}
            port: {{ .Values.gateway.control.containerPort }}
            {{- else }}
            port: {{ .Values.global.servicePorts.gateway }}
            {{- end }}
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 3
          failureThreshold: 2
        readinessProbe:
          httpGet:
            scheme: "HTTP{{ if .Values.global.tls.gateway }}S{{ end }}"
            path: /hello
            {{- if and .Values.gateway.control.enabled (or (semverCompare ">= 3.2.0" (include "tyk-gateway.gateway-version" . )) (semverCompare ">=3.0.4 < 3.1.0" (include "tyk-gateway.gateway-version" .))) }}
            port: {{ .Values.gateway.control.containerPort }}
            {{- else }}
            port: {{ .Values.global.servicePorts.gateway }}
            {{- end }}
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      {{- if .Values.gateway.securityContext }}
      securityContext:
      {{- toYaml .Values.gateway.securityContext | nindent 10 }}
      {{- end }}
      volumes:
        - name: tyk-scratch
          emptyDir: {}
        {{ if .Values.global.tls.gateway }}
        - name: {{ .Values.gateway.tls.secretName }}
          secret:
            secretName: {{ .Values.gateway.tls.secretName }}
        {{ end }}
        {{- if .Values.gateway.extraVolumes }}
        {{- include "tyk-gateway.tplvalues.render" (dict "value" .Values.gateway.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
