{{- if and .Values.gateway.control.enabled .Values.gateway.control.ingress.enabled -}}
{{- $fullName := include "tyk-gateway.fullname" . -}}
{{- $svcPort := .Values.gateway.control.port -}}

{{- if and .Values.gateway.control.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.gateway.control.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.gateway.control.ingress.annotations "kubernetes.io/ingress.class" .Values.gateway.control.ingress.className}}
  {{- end }}
{{- end }}

{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}

kind: Ingress
metadata:
  name: {{ $fullName }}-control
  labels:
    app: gateway-ing-{{ $fullName }}-control 
    chart: {{ include "tyk-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.gateway.control.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.gateway.control.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.gateway.control.ingress.className }}
  {{- end }}
  {{- if .Values.gateway.control.ingress.tls }}
  tls:
    {{- range .Values.gateway.control.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gateway.control.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: gateway-control-svc-{{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: gateway-control-svc-{{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}