{{ if and .Values.gateway.tls.useDefaultTykCertificate .Values.global.tls.gateway }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gateway.tls.secretName }}
type: TLS
data:
  tls.crt: |-
    {{ .Files.Get "certs/tlsCert.pem" | b64enc }}
  tls.key: |-
    {{ .Files.Get "certs/tlsKey.pem" | b64enc }}
{{ end }}