{{ if and .Values.global.tls.useDefaultTykCertificate .Values.global.tls.gateway }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gateway.tls.secretName }}
type: TLS
data:
  tls.crt: |-
    {{ .Files.Get "certs/tlsCert.pem" | b64enc }}
  tls.key: |-
    {{ .Files.Get "certs/tlsKey.pem" | b64enc }}
---
{{ if .Values.gateway.tls.useNewDefaultCertificate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gateway.tls.newSecretName }}
type: TLS
data:
  tls.crt: |-
    {{ .Files.Get "certs/tlsCert-new.pem" | b64enc }}
  tls.key: |-
    {{ .Files.Get "certs/tlsKey-new.pem" | b64enc }}
{{ end }}
{{ end }}
