{{- if not (and .Values.global.secrets.useSecretName ((.Values.global.redis.passSecret).name)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-gateway.fullname" . }}
  labels:
    app: secrets-data-{{ include "tyk-gateway.fullname" . }}
    chart: {{ include "tyk-gateway.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
{{- if not ((.Values.global.redis.passSecret).name) }}
  redisPass: "{{ .Values.global.redis.pass }}"
{{- end }}

{{- if not (.Values.global.secrets.useSecretName) }}
  APISecret: "{{ .Values.global.secrets.APISecret }}"
{{- end -}}

{{- end }}
