apiVersion: v1
kind: Service
metadata:
  name: gateway-svc-{{ include "tyk-gateway.fullname" . }}
  labels:
    app: gateway-svc-{{ include "tyk-gateway.fullname" . }}
    chart: {{ include "tyk-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.gateway.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.gateway.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
  - port: {{ .Values.global.servicePorts.gateway }}
    targetPort: {{ .Values.gateway.containerPort }}
    protocol: TCP
    name: {{ default "http" .Values.gateway.service.portName | quote }}
  selector:
    app: gateway-{{ include "tyk-gateway.fullname" . }}
    release: {{ .Release.Name }}
{{- if eq .Values.gateway.service.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.gateway.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.gateway.service.loadBalancerIP | quote }}
{{- end }}