apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ include "tyk-data-plane.fullname" .}}
  namespace: {{ .Release.Namespace}}
  labels:
    app: secrets-tyk-data-plane
    release: {{ .Release.Name }}
data:
  rpcUseSSL: "{{ .Values.global.remoteControlPlane.useSSL}}"
  rpcSslInsecureSkipVerify: "{{ .Values.global.remoteControlPlane.sslInsecureSkipVerify}}"
