apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-data-plane.fullname" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    app: secrets-tyk-data-plane
    release: {{ .Release.Name }}
type: Opaque
stringData:
  rpcConnString: "{{ .Values.global.remoteControlPlane.connectionString }}"
  orgId: "{{ .Values.global.remoteControlPlane.orgId }}"
  userApiKey: "{{  .Values.global.remoteControlPlane.userApiKey }}"
  APISecret: "{{ .Values.global.secrets.APISecret}}"
  groupID: "{{ .Values.global.remoteControlPlane.groupID}}"
