{{- if .Values.mdcb.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tyk-mdcb.fullname" . }}
  labels:
    {{- include "tyk-mdcb.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mdcb-{{ include "tyk-mdcb.fullname" . }}
  minReplicas: {{ .Values.mdcb.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.mdcb.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.mdcb.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.mdcb.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.mdcb.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          {{ if .Values.mdcb.autoscaling.targetMemoryUtilizationPercentage }}
          averageUtilization: {{ .Values.mdcb.autoscaling.targetMemoryUtilizationPercentage }}
          {{ end }}
    {{- end }}
{{- end }}
