apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-mdcb.fullname" . }}
  labels:
    {{- include "tyk-mdcb.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if not .Values.mdcb.useSecretName }}
  MDCBLicense: "{{ .Values.mdcb.license }}"
  securitySecret: "{{ .Values.mdcb.security.secret }}"
{{- end -}}

{{- if not ((.Values.global.redis.passSecret).name) }}
  redisPass: "{{ .Values.global.redis.pass }}"
{{- end }}

{{- if not ((.Values.global.mongo.connectionURLSecret).name) }}
  mongoURL: {{ include "mdcb.mongo_url" . | quote }}
{{- end }}

{{- if not ((.Values.global.postgres.connectionStringSecret).name) }}
  pgConnectionString: {{ include "mdcb.pg_connection_string" . | quote }}
{{- end }}
