{{ if not .Values.mdcb.useSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: mdcb-{{ include "tyk-mdcb.fullname" . }}
  labels:
    {{- include "tyk-mdcb.labels" . | nindent 4 }}
type: Opaque
data:
  MDCBLicense: {{ .Values.mdcb.license }}
{{ end }}