{{- if .Values.mdcb.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tyk-mdcb.serviceAccountName" . }}
  labels:
    {{- include "tyk-mdcb.labels" . | nindent 4 }}
  {{- with .Values.mdcb.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.mdcb.serviceAccount.automount }}
{{- end }}
